azure:
  activedirectory:
    # Specifies your Active Directory ID:
    tenant-id: ${AZURE_TENANT_ID}
    # Specifies your App Registration's Application ID:
    client-id: ${AZURE_CLIENT_ID}
    # Specifies your App Registration's secret key:
    client-secret: ${AZURE_CLIENT_SECRET}
    # Specifies the post-log-out-redirect-uri, where to return your app after logout.
    # For instance, in the form of http://localhost:8080
    post-logout-redirect-uri: ${REDIRECT_URI}
    # Specifies the Microsoft Graph scopes that your app needs access to - not required in this app.
    # authorization-clients:
    #   graph:
    #     scopes: https://graph.microsoft.com/User.Read

# which routes to restrict to authenticated users only (see SecurityConfig.java):
# enter String array (comma-separated) or just one route.
# e.g. authenticated: /route1, /route2, /route3
app:
  protect:
    authenticated: /token_details

# un-comment the following lines if you are deploying to a reverse proxy (e.g. Azure App Service)
# server:
#   forward-headers-strategy: native
#   tomcat:
#     remoteip:
#       protocol-header: "X-Forwarded-Proto"
#       remote-ip-header: "X-Forwarded-For"
#       internal-proxies: ".*"